# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build  
    jobs:
      - job: Build
        displayName: 'Build job'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '20.x'
          displayName: 'Install Node.js'
        - script: |
            echo 'build $(environment)'
            npm install -g @angular/cli
            npm install
            ng build -c $(environment)
          displayName: 'npm install and build'
        - task: CopyFiles@2
          displayName: 'Copiando arquivos'
          inputs:
            #SourceFolder: # string. Source Folder. 
            Contents: 'dist/exemplo' 
            TargetFolder: '$(Build.ArtifactStagingDirectory)/$(environment)'      
  - stage: Deploy
    dependsOn: Build
    condition: succeeded('Build')
    jobs:
      - job: Deploy
        displayName: 'Deploy job'
        pool:
          vmImage: 'ubuntu-latest'
        steps: 
        - script: |
              echo 'build $(environment)'
        - task: AzureStaticWebApp@0
          inputs:
            skip_app_build: true 
            skip_api_build: true
            workingDirectory: '$(Build.ArtifactStagingDirectory)/$(environment)'
            deployment_environment: $(environment)
            azure_static_web_apps_api_token: $(deployment_token)


          
