# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build  
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          BuildConfiguration: 'Release' 
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '20.x'
          displayName: 'Install Node.js'
        - script: |
            npm install -g @angular/cli
            npm install
            ng build -c $(environment)
          displayName: 'npm install and build'
        - task: ArchiveFiles@2
          displayName: Zip Angular dist folder
          inputs:
            rootFolderOrFile: 'dist/exemplo'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(environment).zip'
            replaceExistingArchive: true  
  - stage: Deploy
    dependsOn: Build
    condition: succeeded('Build')
    jobs:
      - job: 
        steps: 
        - task: AzureStaticWebApp@0
          inputs:
            skip_app_build: true 
            skip_api_build: true
            workingDirectory: '$(Build.ArtifactStagingDirectory)/$(environment)'
            deployment_environment: $(environment)
            azure_static_web_apps_api_token: $(deployment_token)


          
